# Theme configuration
theme: jekyll-theme-cayman
title: Documentation officielle de Square.
description: Tout ce qu'il faut savoir sur Square.
author: C0ZEN
author_email: geoffrey.testelin@gmail.com
permalink: pretty

# Url
homePageUrl: https://c0zen.github.io/Square/
baseUrl: https://c0zen.github.io/Square/

# Users
benUrl: https://github.com/BenoitCompere
benName: BenoitCompere
